bind = ALT, R, submap, resize

submap = resize

$mainMod = SUPER

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod, Tab, cyclenext
bind = $mainMod SHIFT, Tab, cyclenext, prev

binde = , right, resizeactive, 10% 0
binde = , left, resizeactive, -10% 0
binde = , up, resizeactive, 0 -10%
binde = , down, resizeactive, 0 10%
binde = SHIFT, minus, resizeactive, -10% 10%
binde = SHIFT, equal, resizeactive, 10% -10%

bind = , escape, submap, reset
bind = , q, submap, reset
bind = CTRL, c, submap, reset
bind = ALT, R, submap, reset

# Catch all keybind to prevent key events from being passed to the window
# while in submap mode
bind = , catchall, exec, true

submap = reset
