return {}
-- return {
--     {
--         "nvim-neo-tree/neo-tree.nvim",
--         branch = "v3.x",
--         dependencies = {
--             "nvim-lua/plenary.nvim",
--             "nvim-tree/nvim-web-devicons",
--             "MunifTanjim/nui.nvim",
--         },
--         cmd = "Neotree",
--         keys = {
--             { "<leader>e", "<cmd>Neotree toggle<cr>", desc = "Toggle file explorer" },
--         },
--         opts = {
--             close_if_last_window = true, -- Close Neo-tree if it is the last window
--             popup_border_style = "rounded",
--             window = {
--                 width = 30,
--             },
--             filesystem = {
--                 filtered_items = {
--                     visible = true,
--                     hide_dotfiles = false,
--                     hide_gitignored = true,
--                 }
--             }
--         },
--     },
-- }
