animations {
    enabled = yes, please :)
    
    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,              X0,     Y0,     X1,     Y1
    bezier = easeOutQuint,      0.23,   1,      0.32,   1
    bezier = easeInOutCubic,    0.65,   0.05,   0.36,   1
    bezier = linear,            0,      0,      1,      1
    bezier = almostLinear,      0.5,    0.5,    0.75,   1
    bezier = quick,             0.15,   0,      0.1,    1
    # bezier = cyber,             0.05,   0.9,    0.1,    1.05
    bezier = emphasizedDecel,   0.05,   0.07,   0.1,    1
    bezier = emphasizedAccel,   0.3,    0,      0.8,    0.15
    bezier = easeInOutQuart,    0.76,   0,      0.24,   1
    
    # Default animations, see https://wiki.hypr.land/Configuring/Animations/
    #           NAME,                   ONOFF, SPEED,   CURVE,              [STYLE]

    # Global animations
    animation = global,                 1,     10,      default

    # Window animations
    animation = windows,                1,     4.79,    easeOutQuint
    animation = windowsIn,              1,     4.1,     easeOutQuint,       popin 87%
    animation = windowsOut,             1,     1.49,    linear,             popin 87%

    # Fade animations
    animation = fade,                   1,     3.03,    quick
    animation = fadeIn,                 1,     1.73,    almostLinear
    animation = fadeOut,                1,     1.46,    almostLinear
    animation = fadeSwitch,             1,     1,       default
    animation = fadeShadow,             1,     1,       default
    animation = fadeDim,                1,     1,       default
    animation = fadeLayers,             1,     1,       default
    animation = fadeLayersIn,           1,     1.79,    almostLinear
    animation = fadeLayersOut,          1,     1.39,    almostLinear
    animation = fadePopups,             1,     1,       default
    animation = fadePopupsIn,           1,     1,       default
    animation = fadePopupsOut,          1,     1,       default
    animation = fadeDpms,               1,     1,       default

    # Border animations
    animation = border,                 1,     5.39,    easeOutQuint
    animation = borderangle,            1,     1,       default

    animation = workspaces,             1,     1.94,    easeInOutQuart,     slidefade
    animation = workspacesIn,           1,     1.68,    emphasizedDecel,    slidefade
    animation = workspacesOut,          1,     0.84,    emphasizedAccel,    slidefade

    # Special workspace animations
    animation = specialWorkspace,       0,     1,       default
    animation = specialWorkspaceIn,     1,     2.8,     emphasizedDecel,    slidefadevert top
    animation = specialWorkspaceOut,    1,     1.4,     emphasizedAccel,    slidefadevert bottom

    # Zoom animations
    animation = zoomFactor,             1,     7,       quick

    # Monitor added animations
    animation = monitorAdded,           1,     1,       default
    animation = layers,                 1,     3.81,    easeOutQuint
    # animation = layers,                 1,     3.81,    cyber,              fade
    animation = layersIn,               1,     4,       easeOutQuint,       fade
    animation = layersOut,              1,     1.5,     linear,             fade
}
